#!/bin/bash
#
# Filename:     install
# Author:       luca
# Version:      1.0.0
# Date:         2012-09-14
#

CURDIR=`pwd`
HDIR="$HOME/.ete_pystickies"
BIN="$HOME/bin/ete_pystickies"
CFG="$HDIR/ete_pystickiesrc"
[ ! -e "$HDIR" ] && mkdir "$HDIR"

rsync -av "$CURDIR/ete_pystickies" "$BIN"
chmod +x "$BIN"

rsync -av "$CURDIR/ete_pystickiesd" "$HDIR/"
chmod +x "$HDIR/ete_pystickiesd"

sudo rsync -v "$CURDIR/ete_pystickies.completion" "/etc/bash_completion.d/ete_pystickies"

if [ ! -e $CFG ]; then
    cp "$CURDIR/ete_pystickiesrc.sample" "$CFG"
    echo -e "\n####\n# REMEMBER TO EDIT YOUR CONFIG $CFG\n###"
    if [ ! -z $EDITOR ]; then
        $EDITOR "$CFG"
    fi
fi
